# Generated by Django 5.1.2 on 2024-10-29 05:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="video_url",
        ),
        migrations.AddField(
            model_name="video",
            name="video_file",
            field=models.FileField(
                default=1,
                upload_to="videos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov", "avi"]
                    )
                ],
            ),
            preserve_default=False,
        ),
    ]
